/* SPDX-License-Identifier: MIT */
/*
 * trace_gen - parameterized checkpoint trace generator + analytical model.
 *
 * P8 borrows the LLMServingSim request-trace idea and turns it into a
 * checkpoint trace: a deterministic sequence of checkpoint events
 * (step, ckpt_id, size_bytes) generated from {size, chunk_size, interval,
 * num_ckpts, hot_frac}. The trace is identical to the one generated by
 * analytical_model.py, so the analytical model and the cycle simulator replay
 * the *same* workload.
 *
 * This header also carries the calibrated baselines (P0/P2/P5) used by the
 * analytical model (trace_model.c replays them host-side, ckptbench_p8 measures
 * the cycle-sim ground truth).
 */
#ifndef TRACE_GEN_H
#define TRACE_GEN_H

#include <stdint.h>

/* --- Calibrated baselines (see exec_summary.md / readme_cxl.md) --------- */
#define B_GPU_DRAM    30e9    /* GPU -> DRAM write (B/s)                    */
#define B_GPU_CXL     30e9    /* GPU -> CXL  write (B/s)                    */
#define B_DRAM_READ   29e9    /* DRAM -> device read (B/s)                  */
#define B_CXL_READ    20e9    /* CXL  -> device read (B/s)                  */
#define B_DRAM_WRITE  29e9    /* device -> DRAM write (B/s)                 */
#define B_CXL_WRITE   30e9    /* device -> CXL  write (B/s)                 */
#define B_CHANNEL     7.2e9   /* one storage channel (B/s)                  */

/* Serial (single-engine) per-chunk latencies, guest-simulated time (P5/P7). */
#define T_SAVE_CHUNK        98e-6   /* memory -> storage, one 4 KiB chunk   */
#define T_RESTORE_COLD      102e-6  /* storage -> memory, one 4 KiB chunk   */
#define T_RESTORE_HOT       14e-6   /* CXL hot standby -> memory (memcpy)   */
#define T_STARTUP           1e-3    /* DMA pipeline cold start + tail drain */

/* Topology identifiers (match analytical_model.py). */
#define TOPO_DRAM 0
#define TOPO_CXL  1
#define TOPO_BOTH 2

#define TRACE_MAX_CKPTS 64

struct ckpt_trace_event {
    uint64_t step;
    uint32_t ckpt_id;
    uint64_t size_bytes;
};

struct ckpt_trace {
    uint64_t chunk_size;
    double   hot_frac;                 /* hot fraction of each checkpoint     */
    uint32_t num_ckpts;
    uint32_t n_chunks;                 /* chunks per checkpoint               */
    uint32_t hot_cap;                  /* CXL hot-standby capacity (chunks)   */
    struct ckpt_trace_event events[TRACE_MAX_CKPTS];
};

/* Generate a deterministic trace (identical to analytical_model.py). */
void trace_generate(struct ckpt_trace *t, uint64_t size_bytes,
                    uint64_t chunk_size, uint64_t interval,
                    uint32_t num_ckpts, double hot_frac);

/* --- analytical model (host-side; mirrors analytical_model.py) ---------- */

double model_gpu_ingress(int topology);
double model_mem_egress(int topology);
double model_bsave_bound(int topology, int n_channels);
double model_bresume_bound(int topology, int n_channels);

/* Serial (latency-limited) predictions for the single-engine device. */
double model_serial_save_time(const struct ckpt_trace *t);
double model_serial_resume_time(const struct ckpt_trace *t, uint32_t restore_ckpt,
                                double *hit_rate_out);

/* True if chunk (ckpt_id, chunk_id) is still in the CXL hot standby after the
 * whole trace has been saved in order (equivalent to the LRU in trace_gen.c:
 * the most-recent hot_cap global chunk ids are hot). */
int trace_chunk_is_hot(const struct ckpt_trace *t, uint32_t ckpt_id,
                       uint32_t chunk_id);

#endif /* TRACE_GEN_H */
